/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-11-22 05:35:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1478764460021L));
    _jspx_dependants.put("jar:file:/D:/KOSTA/깃허브/CtrlZ/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FMS/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/KOSTA/깃허브/CtrlZ/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FMS/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\" />\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("<!-- Description, Keywords and Author -->\r\n");
      out.write("\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<title>:: Floxi ::</title>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/html/images/favicon.ico\" type=\"/html/image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("<!-- style -->\r\n");
      out.write("\r\n");
      out.write("<link href=\"/html/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- style -->\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap -->\r\n");
      out.write("\r\n");
      out.write("<link href=\"/html/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- responsive -->\r\n");
      out.write("\r\n");
      out.write("<link href=\"/html/css/responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- font-awesome -->\r\n");
      out.write("\r\n");
      out.write("<link href=\"/html/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- font-awesome -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- side bar -->\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/side.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- side bar --> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- header -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- header --> \r\n");
      out.write("\r\n");
      out.write("<!-- main -->\r\n");
      out.write("\r\n");
      out.write("<main role=\"main\" id=\"main\">\r\n");
      out.write("  <div class=\"container\"> \r\n");
      out.write("    \r\n");
      out.write("    <!-- tab-content -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"tab-content\"> \r\n");
      out.write("      \r\n");
      out.write("      <!-- Home -->\r\n");
      out.write("      \r\n");
      out.write("      <section id=\"home\" class=\"tab-pane fade in active\">\r\n");
      out.write("          <article class=\"home-content\">\r\n");
      out.write("            <header role=\"home-title\">\r\n");
      out.write("              <h2>F.M.S\r\n");
      out.write("                <div id=\"typed-strings\"><span>원활한 축구팀관리!</span> <span>의사소통도 편리하게 관리!</span> <span>FMS(풋볼 매니지먼트 솔루션!)</span> </div>\r\n");
      out.write("                <span id=\"typed\" style=\"white-space:pre;\"></span></h2>\r\n");
      out.write("            </header>\r\n");
      out.write("            <p>We're sorry, our website is now under construction. We are working<br/>\r\n");
      out.write("              hard to deliver you a great viewing experience!\r\n");
      out.write("            <p> \r\n");
      out.write("          </article>\r\n");
      out.write("          <div id=\"countdown\"></div>\r\n");
      out.write("        </section>\r\n");
      out.write("      \r\n");
      out.write("      <!-- Home --> \r\n");
      out.write("      \r\n");
      out.write("      <!-- about -->\r\n");
      out.write("      \r\n");
      out.write("      <section id=\"menu1\" class=\"tab-pane fade other-page about-pan\">\r\n");
      out.write("          <header role=\"page-title\">\r\n");
      out.write("            <h2>F.M.S(풋볼 매니지먼트 솔루션)이란...?</h2>\r\n");
      out.write("          </header>\r\n");
      out.write("          <article>\r\n");
      out.write("            <p>FMS. \"풋볼매니지먼트 솔루션\"은  축구동호호나 기타 아날로그로 적어가던 축구 시스템을 디지털 방식으로 보여주기 위해 만들었습니다. </p>\r\n");
      out.write("            <p>현재로는, 한명의 관리자와 여러명의 회원을 가지고 사용하는 1인감독의 축구 관리 시스템 입니다만. 앞으로는 여러팀과 여러 관리자들도 만들어, 매칭 시스템도 구현하려는 계획을 가지고있습니다</p>\r\n");
      out.write("            <p><b>본 프로젝트는 코스타 126기 Ctrl+Z조가 만들었습니다</b></p>\r\n");
      out.write("            <label>----------------------------------------------------------------</label>\r\n");
      out.write("                   <br>\r\n");
      out.write("            <label style=\"color:white; font-size: 20px;\"><b>조장  : 안광호</b></label> \r\n");
      out.write("            <p>조원  : 임영묵, 김민호, 강준, 박찬용</p>\r\n");
      out.write("          </article>\r\n");
      out.write("        </section>\r\n");
      out.write("      \r\n");
      out.write("      <!-- about --> \r\n");
      out.write("      \r\n");
      out.write("      <!-- Newsletter Subscribtion -->\r\n");
      out.write("      \r\n");
      out.write("      <section id=\"menu2\" class=\"tab-pane fade other-page\">\r\n");
      out.write("        <header role=\"page-title\">\r\n");
      out.write("          <h2>Newsletter Subscribtion</h2>\r\n");
      out.write("        </header>\r\n");
      out.write("        <article>\r\n");
      out.write("          <p>Mauris rutrum risus ac luctus cursus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent vel quam id mi finibus tempor. </p>\r\n");
      out.write("          \r\n");
      out.write("          <!-- subscribe -->\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"subscribe-pan\">\r\n");
      out.write("            <div class=\"ntify_form\">\r\n");
      out.write("              <form method=\"post\" action=\"/html/php/subscribe.php\" name=\"subscribeform\" id=\"subscribeform\">\r\n");
      out.write("                <input name=\"email\" type=\"email\" id=\"subemail\" placeholder=\"Enter Your Email...\">\r\n");
      out.write("                <label>\r\n");
      out.write("                  <input name=\"\" type=\"submit\" class=\"button-icon\">\r\n");
      out.write("                  <i class=\"fa fa-paper-plane\" aria-hidden=\"true\"></i> </label>\r\n");
      out.write("              </form>\r\n");
      out.write("              \r\n");
      out.write("              <!-- subscribe message -->\r\n");
      out.write("              \r\n");
      out.write("              <div id=\"mesaj\"></div>\r\n");
      out.write("              \r\n");
      out.write("              <!-- subscribe message --> \r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <!-- subscribe --> \r\n");
      out.write("          \r\n");
      out.write("        </article>\r\n");
      out.write("      </section>\r\n");
      out.write("      \r\n");
      out.write("      <!-- Newsletter Subscribtion --> \r\n");
      out.write("      \r\n");
      out.write("      <!-- Contact -->\r\n");
      out.write("      \r\n");
      out.write("      <section id=\"menu3\" class=\"tab-pane fade other-page\">\r\n");
      out.write("        <header role=\"page-title\">\r\n");
      out.write("          <h2>Contact us</h2>\r\n");
      out.write("        </header>\r\n");
      out.write("        <article>\r\n");
      out.write("          <p>Mauris rutrum risus ac luctus cursus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent vel quam id mi finibus tempor. </p>\r\n");
      out.write("        </article>\r\n");
      out.write("        \r\n");
      out.write("        <!-- form -->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"contact-from row\">\r\n");
      out.write("          <div class=\"col-md-7 col-lg-7\">\r\n");
      out.write("            <div id=\"message\"></div>\r\n");
      out.write("            <form method=\"post\" action=\"/html/php/contact.php\" name=\"cform\" id=\"cform\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-sm-6\">\r\n");
      out.write("                  <input  name=\"name\" id=\"name\" type=\"text\" placeholder=\"Enter Your Name...\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-sm-6\">\r\n");
      out.write("                  <input  name=\"email\" id=\"email\" type=\"email\"  placeholder=\"Enter Your Email...\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"clearfix\"></div>\r\n");
      out.write("              <textarea name=\"comments\" id=\"comments\" cols=\"\" rows=\"\" placeholder=\"Enter Your Description...\"></textarea>\r\n");
      out.write("              <div class=\"clearfix\"></div>\r\n");
      out.write("              <input name=\"\" type=\"submit\" value=\"Submit\">\r\n");
      out.write("              <div id=\"simple-msg\"></div>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"clearfix\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- form --> \r\n");
      out.write("        \r\n");
      out.write("      </section>\r\n");
      out.write("      \r\n");
      out.write("      <!-- Contact --> \r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- tab-content --> \r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<!-- main --> \r\n");
      out.write("\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery (necessary for Bootstrap's JavaScript plugins) --> \r\n");
      out.write("\r\n");
      out.write("<script src=\"/html/js/jquery.min.js\" type=\"text/javascript\"></script> \r\n");
      out.write("\r\n");
      out.write("<!-- custom --> \r\n");
      out.write("\r\n");
      out.write("<script src=\"/html/js/custom.js\" type=\"text/javascript\"></script> \r\n");
      out.write("<script src=\"/html/js/nav-custom.js\" type=\"text/javascript\"></script> \r\n");
      out.write("\r\n");
      out.write("<!-- Include all compiled plugins (below), or include individual files as needed --> \r\n");
      out.write("\r\n");
      out.write("<script src=\"/html/js/bootstrap.min.js\" type=\"text/javascript\"></script> \r\n");
      out.write("\r\n");
      out.write("<!-- jquery.countdown --> \r\n");
      out.write("\r\n");
      out.write("<script src=\"/html/js/countdown-js.js\" type=\"text/javascript\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"/html/js/jquery.contact.js\"></script> \r\n");
      out.write("<script src=\"/html/js/html5shiv.js\" type=\"text/javascript\"></script> \r\n");
      out.write("\r\n");
      out.write("<!-- Typed jS --> \r\n");
      out.write("\r\n");
      out.write("<script src=\"/html/js/typed.js\" type=\"text/javascript\"></script> \r\n");
      out.write("<script>\r\n");
      out.write("    $(function(){\r\n");
      out.write("\r\n");
      out.write("        $(\"#typed\").typed({\r\n");
      out.write("            // strings: [\"Typed.js is a <strong>jQuery</strong> plugin.\", \"It <em>types</em> out sentences.\", \"And then deletes them.\", \"Try it out!\"],\r\n");
      out.write("            stringsElement: $('#typed-strings'),\r\n");
      out.write("            typeSpeed: 100,\r\n");
      out.write("            backDelay: 1000,\r\n");
      out.write("            loop: true,\r\n");
      out.write("            contentType: 'html', // or text\r\n");
      out.write("            // defaults to false for infinite loop\r\n");
      out.write("            loopCount: false,\r\n");
      out.write("            callback: function(){ foo(); },\r\n");
      out.write("            resetCallback: function() { newTyped(); }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(\".reset\").click(function(){\r\n");
      out.write("            $(\"#typed\").typed('reset');\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function newTyped(){ /* A new typed object */ }\r\n");
      out.write("\r\n");
      out.write("    function foo(){ console.log(\"Callback\"); }\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
